#!/usr/bin/env bash

# Post provisioning script
# sudo apt update -y && sudo apt upgrade -y && \
# sudo apt install -y php7.1 php7.1-cli php7.1-fpm php7.1-common php7.1-gd php7.1-mcrypt php7.1-mbstring php7.1-xml php7.1-mysql php7.1-pgsql php7.1-sqlite3 php7.1-zip php7.1-soap  php7.1-xmlrpc && \
# composer global require friendsofphp/php-cs-fixer && \
# composer global update

